import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const routesData = require('../data/routes.json'); // structured route/fare data

// KML-derived route metadata (generated by scripts/extract-kml-routes.js).
let kmlRoutes = [];
try {
  kmlRoutes = require('../data/route-descriptions.json');
} catch {
  kmlRoutes = [];
}

// Merge the structured JSON with the richer KML descriptions by route code.
const kmlByCode = new Map(kmlRoutes.map((r) => [r.code, r]));
const routeData = routesData.map((r) => {
  const kml = kmlByCode.get(r.code);
  return {
    code: r.code,
    route: r.route,
    group: r.group,
    via: r.via,
    stops: r.stops,
    name: kml?.name || r.route,
    description: kml?.description || '',
  };
});

function readBody(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (chunk) => {
      data += chunk;
    });
    req.on('end', () => {
      try {
        resolve(JSON.parse(data || '{}'));
      } catch {
        resolve({});
      }
    });
  });
}

export default async function handler(req, res) {
  // Make the handler work both as a Vercel function and as a connect-style
  // middleware (Vite dev server), where res lacks .status()/.json().
  if (typeof res.status !== 'function') {
    res.status = (code) => {
      res.statusCode = code;
      return res;
    };
  }
  if (typeof res.json !== 'function') {
    res.json = (obj) => {
      res.setHeader('Content-Type', 'application/json');
      res.end(JSON.stringify(obj));
    };
  }

  if (req.method !== 'POST') return res.status(405).end();

  // Vercel pre-parses req.body; connect-style middleware (Vite dev) does not.
  let body = req.body;
  if (typeof body === 'string') {
    try {
      body = JSON.parse(body);
    } catch {
      body = {};
    }
  } else if (body == null) {
    body = await readBody(req);
  }

  const { message } = body;

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({
      reply: 'Chat is not configured yet — add GEMINI_API_KEY to your .env file.',
    });
  }

  const routeRef = routeData
    .map((r) => {
      const parts = [`${r.code}: ${r.name}`];
      if (r.via) parts.push(`via ${r.via}`);
      if (r.stops?.length) parts.push(`stops: ${r.stops.join(', ')}`);
      if (r.description) parts.push(`route: ${r.description.split('\n').join(' -> ')}`);
      return parts.join(' | ');
    })
    .join('\n');

  const systemPrompt = `You are a Cebu jeepney travel assistant for Route7.
Only answer using the route data below. Do not invent routes or fares that are not listed.

Route data:
${routeRef}

Reply rules:
- Give only the single best/most direct route by default. Only list alternatives if the user explicitly asks for other options.
- Keep the reply to 2-4 short sentences max. No headers, no bullet lists, no numbered lists, no markdown formatting (no asterisks, no bold). Plain conversational text only.
- Mention the route code/name, a one-line via/stops summary, and the fare if it's in the data.
- If the question is outside the route/fare data, say so briefly instead of guessing.`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: `${systemPrompt}\n\nUser question: ${message}` }] }]
      })
    }
  );

  const data = await response.json();
  const reply = data.candidates?.[0]?.content?.parts?.[0]?.text
    ?? data.error?.message
    ?? "Sorry, I couldn't get an answer.";
  res.status(200).json({ reply });
}